# NumPy - Python 数值计算基石教程

欢迎来到 NumPy 教程！NumPy (Numerical Python) 是 Python 科学计算生态系统的核心库。它提供了一个强大的 N 维数组对象 (`ndarray`)，以及用于高效处理这些数组的各种函数。

**为什么 NumPy 对 ML/DL/数据科学如此重要？**

1.  **高效的数值运算**：NumPy 的核心是用 C 语言编写的，其数组操作（向量化操作）比纯 Python 的列表循环快得多。
2.  **`ndarray` 对象**：提供了一个同构（所有元素类型相同）、多维、固定大小的数组，非常适合表示数值数据、向量、矩阵、图像等。
3.  **数学函数库**：包含大量的数学、线性代数、傅里叶变换和随机数生成函数。
4.  **生态系统基础**：Pandas, Scikit-learn, SciPy, Matplotlib, PyTorch, TensorFlow 等几乎所有科学计算和 ML/DL 库都建立在 NumPy 之上或与之紧密集成。

**本教程将涵盖 NumPy 的核心概念和常用操作：**

1.  创建 NumPy 数组 (`ndarray`)
2.  数组的基本属性
3.  数组索引和切片
4.  向量化操作和通用函数 (ufuncs)
5.  广播 (Broadcasting)
6.  基本线性代数
7.  随机数生成
8.  数组形状操作

## 准备工作：导入 NumPy

按照惯例，我们将 NumPy 导入并简写为 `np`。

In [ ]:
import numpy as np

print(f"NumPy version: {np.__version__}")

## 1. 创建 NumPy 数组 (`ndarray`)

有多种方法可以创建 NumPy 数组：

In [ ]:
# 从 Python 列表或元组创建
list_data = [1, 2, 3, 4, 5]
arr_from_list = np.array(list_data)
print(f"Array from list: {arr_from_list}")
print(f"Type: {type(arr_from_list)}")

tuple_data = (6, 7, 8)
arr_from_tuple = np.array(tuple_data)
print(f"Array from tuple: {arr_from_tuple}")

# 创建多维数组 (例如，从嵌套列表)
nested_list = [[1, 2, 3], [4, 5, 6]]
arr_2d = np.array(nested_list)
print(f"\n2D Array:\n{arr_2d}")

# 使用内置函数创建特定数组
arr_zeros = np.zeros((2, 3)) # 创建一个 2x3 的全零数组 (默认 float64)
print(f"\nZeros array (2x3):\n{arr_zeros}")

arr_ones = np.ones((3, 2), dtype=int) # 创建一个 3x2 的全一数组，指定类型为 int
print(f"\nOnes array (3x2, int):\n{arr_ones}")

arr_full = np.full((2, 2), 7.5) # 创建一个 2x2 的数组，所有元素填充为 7.5
print(f"\nFull array (2x2, fill 7.5):\n{arr_full}")

arr_eye = np.eye(3) # 创建一个 3x3 的单位矩阵
print(f"\nIdentity matrix (3x3):\n{arr_eye}")

# 使用序列生成函数
arr_arange = np.arange(0, 10, 2) # 类似 Python 的 range，但不包含结束值，可以有步长
print(f"\nArray from arange(0, 10, 2): {arr_arange}")

arr_linspace = np.linspace(0, 1, 5) # 在 [0, 1] 之间生成 5 个等间隔的数 (包含结束值)
print(f"\nArray from linspace(0, 1, 5): {arr_linspace}")

# 使用随机数函数
arr_rand = np.random.rand(2, 2) # 生成 [0, 1) 之间的均匀分布随机数 (2x2)
print(f"\nRandom array (2x2, uniform [0,1)):\n{arr_rand}")

arr_randn = np.random.randn(3, 1) # 生成符合标准正态分布 (均值0, 方差1) 的随机数 (3x1)
print(f"\nRandom array (3x1, standard normal):\n{arr_randn}")

arr_randint = np.random.randint(0, 10, size=(2, 4)) # 生成 [0, 10) 之间的随机整数 (2x4)
print(f"\nRandom integer array (2x4, [0,10)):\n{arr_randint}")

## 2. 数组的基本属性

每个 `ndarray` 对象都有一些描述其自身的属性：

In [ ]:
arr = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
print(f"Array:\n{arr}")

# shape: 数组的维度 (一个元组)
print(f"Shape: {arr.shape}") # (2, 3) -> 2 行 3 列

# ndim: 数组的轴（维度）的数量
print(f"Number of dimensions (ndim): {arr.ndim}") # 2

# dtype: 数组中元素的数据类型
print(f"Data type (dtype): {arr.dtype}") # float64 (默认)

# size: 数组中元素的总数
print(f"Total number of elements (size): {arr.size}") # 6

# itemsize: 数组中每个元素的字节大小
print(f"Size of each element in bytes (itemsize): {arr.itemsize}") # 8 (float64 是 8 字节)

# nbytes: 整个数组占用的总字节数 (size * itemsize)
print(f"Total bytes consumed by the elements (nbytes): {arr.nbytes}") # 48

## 3. 数组索引和切片

NumPy 数组的索引和切片非常灵活，对于数据访问和操作至关重要。

In [ ]:
# 一维数组索引和切片 (类似 Python 列表)
arr1d = np.arange(10)
print(f"1D Array: {arr1d}")
print(f"Element at index 3: {arr1d[3]}")
print(f"Elements from index 2 to 5 (exclusive): {arr1d[2:5]}")
print(f"Elements from index 5 onwards: {arr1d[5:]}")
print(f"Elements up to index 4 (exclusive): {arr1d[:4]}")
print(f"Every other element: {arr1d[::2]}")
print(f"Reverse array: {arr1d[::-1]}")

# 多维数组索引和切片
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"\n2D Array:\n{arr2d}")

# 访问单个元素: arr[row, column]
print(f"Element at row 1, col 2: {arr2d[1, 2]}") # 6
# 或者使用 arr[row][column]，但这通常效率较低，因为它创建了中间数组
print(f"Element using arr[1][2]: {arr2d[1][2]}") # 6

# 切片：使用逗号分隔不同维度的切片
print(f"\nFirst 2 rows, columns 1 to 3 (exclusive):\n{arr2d[:2, 1:3]}")
# [[2 3]
#  [5 6]]

print(f"\nRow at index 1: {arr2d[1, :]}") # 或 arr2d[1]
# [4 5 6]

print(f"\nColumn at index 1:\n{arr2d[:, 1]}")
# [2 5 8] (注意返回的是一维数组)

# *** NumPy 切片是视图 (Views) ***
# 对切片的修改会影响原始数组！
arr2d_slice = arr2d[:2, :2]
print(f"\nOriginal slice:\n{arr2d_slice}")
arr2d_slice[0, 0] = 99
print(f"Slice after modification:\n{arr2d_slice}")
print(f"Original arr2d after slice modification:\n{arr2d}") # 原始数组也被改变了!

# 如果需要副本，使用 .copy()
arr2d_copy = arr2d[:2, :2].copy()
arr2d_copy[0, 0] = 111
print(f"\nCopy after modification:\n{arr2d_copy}")
print(f"Original arr2d (should be unchanged by copy modification):\n{arr2d}")

# *** 高级索引 ***
print("\n--- Advanced Indexing ---")
arr_adv = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 1. 整数数组索引: 使用整数数组指定索引
# 获取第0行和第2行的所有列
print(f"Rows 0 and 2:\n{arr_adv[[0, 2]]}") 
# 获取元素 (0, 1), (1, 2), (2, 0)
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])
print(f"Elements at (0,1), (1,2), (2,0): {arr_adv[row_indices, col_indices]}") # [2 6 7]

# 2. 布尔索引: 使用布尔数组选择元素
bool_mask = arr_adv > 5
print(f"\nBoolean mask (arr_adv > 5):\n{bool_mask}")
print(f"Elements greater than 5: {arr_adv[bool_mask]}") # 返回一个包含满足条件元素的一维数组

# 也可以直接使用条件
print(f"Elements where arr_adv % 2 == 0: {arr_adv[arr_adv % 2 == 0]}")

# *** 注意：高级索引总是返回数组的副本，而不是视图！***

## 4. 向量化操作和通用函数 (ufuncs)

NumPy 的核心优势在于其**向量化 (vectorization)** 能力。这意味着许多操作可以应用于整个数组，而无需编写显式的 Python 循环。这些操作通常是通过**通用函数 (universal functions, ufuncs)** 实现的，它们底层是用 C 编写的，非常高效。

**好处：**
*   代码更简洁、更易读。
*   执行速度快得多。

In [ ]:
arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6])

# 基本算术运算 (element-wise)
print(f"arr_a + arr_b = {arr_a + arr_b}")
print(f"arr_a - arr_b = {arr_a - arr_b}")
print(f"arr_a * arr_b = {arr_a * arr_b}") # 逐元素乘法
print(f"arr_a / arr_b = {arr_a / arr_b}")
print(f"arr_a ** 2 = {arr_a ** 2}")

# 也可以和标量运算 (利用了广播，见下一节)
print(f"arr_a + 5 = {arr_a + 5}")
print(f"arr_a * 2 = {arr_a * 2}")

# 比较运算 (element-wise)
print(f"\narr_a > 1 = {arr_a > 1}") # 返回布尔数组
print(f"arr_a == arr_b = {arr_a == arr_b}")

# 通用函数 (ufuncs)
print(f"\nnp.sqrt(arr_a) = {np.sqrt(arr_a)}")
print(f"np.exp(arr_a) = {np.exp(arr_a)}") # e^x
print(f"np.sin(arr_a) = {np.sin(arr_a)}")
print(f"np.log(arr_a) = {np.log(arr_a)}") # 自然对数
print(f"np.add(arr_a, arr_b) = {np.add(arr_a, arr_b)}") # 等同于 arr_a + arr_b
print(f"np.maximum(arr_a, np.array([0, 5, 2])) = {np.maximum(arr_a, np.array([0, 5, 2]))}") # 逐元素取最大值

# 聚合函数
arr_agg = np.array([[1, 2, 3], [4, 5, 6]])
print(f"\nArray for aggregation:\n{arr_agg}")
print(f"Sum of all elements: {np.sum(arr_agg)} or {arr_agg.sum()}")
print(f"Sum along columns (axis=0): {np.sum(arr_agg, axis=0)} or {arr_agg.sum(axis=0)}") # [5 7 9]
print(f"Sum along rows (axis=1): {np.sum(arr_agg, axis=1)} or {arr_agg.sum(axis=1)}") # [ 6 15]
print(f"Minimum value: {np.min(arr_agg)} or {arr_agg.min()}")
print(f"Maximum value in each column: {np.max(arr_agg, axis=0)}") # [4 5 6]
print(f"Mean of all elements: {np.mean(arr_agg)} or {arr_agg.mean()}")
print(f"Standard deviation: {np.std(arr_agg)} or {arr_agg.std()}")

## 5. 广播 (Broadcasting)

广播是 NumPy 强大的机制，它允许 NumPy 在执行算术运算时处理不同形状的数组，前提是它们的形状满足一定的兼容性规则。

**广播规则：**
当对两个数组进行操作时，NumPy 逐个比较它们的维度（从末尾维度开始向前比较）：
1.  如果两个数组的维度数不同，将维度较少的数组的形状在前面补 1，直到它们的维度数相同。
2.  在任何一个维度上，如果两个数组的该维度大小相同，或者其中一个数组的大小为 1，则认为它们在该维度上是兼容的。
3.  如果两个数组在所有维度上都兼容，它们就可以一起广播。
4.  广播后，每个数组的行为就像其形状沿大小为 1 的维度扩展（复制）以匹配另一个数组的形状一样。
5.  如果存在任何一个维度，两个数组的大小都大于 1 且不相同，则无法广播，会引发 `ValueError`。

In [ ]:
# 示例 1: 标量和数组
arr = np.array([1, 2, 3])
scalar = 5
# arr shape: (3,)
# scalar conceptually has shape ()
# Broadcasting makes scalar act like [5, 5, 5]
result = arr + scalar
print(f"Array + Scalar:\n {arr} + {scalar} = {result}")

# 示例 2: 一维数组和二维数组
arr2d = np.array([[10, 20, 30], [40, 50, 60]]) # shape (2, 3)
arr1d = np.array([1, 2, 3])               # shape (3,)
# Broadcasting rules:
# arr2d shape: (2, 3)
# arr1d shape: (   3,) -> promoted to (1, 3)
# Dimension 2: 3 == 3 (compatible)
# Dimension 1: 2 vs 1 (compatible, 1 will be stretched)
# arr1d acts like [[1, 2, 3], [1, 2, 3]]
result = arr2d + arr1d
print(f"\n2D Array + 1D Array:\n{arr2d}\n + \n{arr1d}\n = \n{result}")

# 示例 3: 列向量和行向量
col_vector = np.array([[10], [20], [30]]) # shape (3, 1)
row_vector = np.array([1, 2, 3])          # shape (3,) -> treated as (1, 3)
# Broadcasting rules:
# col_vector shape: (3, 1)
# row_vector shape: (1, 3)
# Dimension 2: 1 vs 3 (compatible, 1 stretched to 3)
# Dimension 1: 3 vs 1 (compatible, 1 stretched to 3)
# col acts like [[10, 10, 10], [20, 20, 20], [30, 30, 30]]
# row acts like [[ 1,  2,  3], [ 1,  2,  3], [ 1,  2,  3]]
result = col_vector + row_vector
print(f"\nColumn Vector + Row Vector:\n{col_vector}\n + \n{row_vector}\n = \n{result}")

# 示例 4: 不兼容的形状
arr_a = np.array([[1, 2], [3, 4]]) # shape (2, 2)
arr_b = np.array([10, 20, 30])     # shape (3,)
try:
    result = arr_a + arr_b
except ValueError as e:
    print(f"\nError broadcasting incompatible shapes (2,2) and (3,): {e}")

## 6. 基本线性代数

NumPy 提供了进行线性代数运算的功能，这在 ML/DL 中非常常用。
*   **矩阵乘法**: 可以使用 `@` 运算符 (Python 3.5+) 或 `np.dot()` 函数。
*   **其他运算**: 位于 `np.linalg` 子模块中，如求逆、行列式、特征值、奇异值分解 (SVD) 等。

In [ ]:
mat_a = np.array([[1, 2], [3, 4]]) # 2x2 matrix
mat_b = np.array([[5, 6], [7, 8]]) # 2x2 matrix
vec_v = np.array([10, 20])         # 1D vector (shape (2,))

print(f"Matrix A:\n{mat_a}")
print(f"Matrix B:\n{mat_b}")
print(f"Vector V: {vec_v}")

# 逐元素乘法 (回顾)
print(f"\nElement-wise product A * B:\n{mat_a * mat_b}")

# 矩阵乘法 (Dot Product / Matrix Multiplication)
# 1. 使用 @ 运算符 (推荐)
mat_product = mat_a @ mat_b 
print(f"\nMatrix product A @ B:\n{mat_product}")

# 2. 使用 np.dot()
mat_product_dot = np.dot(mat_a, mat_b)
print(f"Matrix product np.dot(A, B):\n{mat_product_dot}")

# 矩阵与向量乘法
mat_vec_product = mat_a @ vec_v # or np.dot(mat_a, vec_v)
print(f"\nMatrix-vector product A @ V: {mat_vec_product}") # Result is 1D array [50, 110]

# 转置 (Transpose)
print(f"\nTranspose of A (A.T):\n{mat_a.T}")
print(f"Transpose using np.transpose(A):\n{np.transpose(mat_a)}")

# 矩阵求逆 (Inverse) - 仅对方阵且可逆矩阵有效
try:
    mat_a_inv = np.linalg.inv(mat_a)
    print(f"\nInverse of A:\n{mat_a_inv}")
    # 验证 A @ A_inv 约等于单位矩阵
    print(f"A @ A_inv (should be close to identity):\n{mat_a @ mat_a_inv}")
except np.linalg.LinAlgError as e:
    print(f"\nCould not compute inverse of A: {e}")

# 行列式 (Determinant)
det_a = np.linalg.det(mat_a)
print(f"\nDeterminant of A: {det_a:.2f}")

# 奇异值分解 (Singular Value Decomposition - SVD)
U, s, Vh = np.linalg.svd(mat_a)
print("\nSVD of A:")
print(f"  U:\n{U}")
print(f"  Singular values (s): {s}")
print(f"  Vh (V transpose):\n{Vh}")

## 7. 随机数生成

`np.random` 模块提供了更丰富、更高效的随机数生成功能，常用于权重初始化、数据增强、模拟等。

In [ ]:
# 设置随机种子以保证结果可复现
np.random.seed(42)

# 生成均匀分布 [0.0, 1.0)
rand_uniform = np.random.rand(3, 2) # 3x2 array
print(f"Uniform random [0,1) (3x2):\n{rand_uniform}")

# 生成标准正态分布 (mean=0, std=1)
rand_normal = np.random.randn(4) # 1D array of size 4
print(f"\nStandard normal random (size 4): {rand_normal}")

# 生成随机整数 [low, high)
rand_int = np.random.randint(1, 100, size=5) # 5 integers from [1, 100)
print(f"\nRandom integers [1, 100): {rand_int}")

# 从数组中随机选择 (有放回或无放回)
population = np.arange(10)
choice_replace = np.random.choice(population, size=5, replace=True) # 有放回
print(f"\nRandom choice (with replacement) from {population}: {choice_replace}")
choice_no_replace = np.random.choice(population, size=5, replace=False) # 无放回
print(f"Random choice (without replacement) from {population}: {choice_no_replace}")

# 打乱数组 (原地操作)
arr_to_shuffle = np.arange(9)
np.random.shuffle(arr_to_shuffle)
print(f"\nShuffled array: {arr_to_shuffle}")

# 生成特定分布的随机数 (例如，正态分布)
mu, sigma = 10, 2 # 均值和标准差
normal_dist = np.random.normal(mu, sigma, size=5)
print(f"\nNormal distribution (mean=10, std=2): {normal_dist}")

## 8. 数组形状操作

改变数组的形状而不改变其数据，是常见的操作。

In [ ]:
arr = np.arange(12) # [ 0  1  2  3  4  5  6  7  8  9 10 11]
print(f"Original array: {arr}, shape: {arr.shape}")

# reshape(): 返回一个具有新形状的数组 (视图或副本，取决于内存布局)
reshaped_arr = arr.reshape((3, 4))
print(f"\nReshaped array (3x4):\n{reshaped_arr}")
print(f"Shape after reshape: {reshaped_arr.shape}")

# -1 可以表示推断维度大小
reshaped_auto = arr.reshape((2, -1)) # -1 会自动计算为 6
print(f"\nReshaped array (2x-1):\n{reshaped_auto}")
print(f"Shape with -1: {reshaped_auto.shape}")

# ravel() or flatten(): 将多维数组展平成一维数组
# ravel() 通常返回视图 (如果可能)
raveled_arr = reshaped_arr.ravel()
print(f"\nRaveled array: {raveled_arr}")
# flatten() 总是返回副本
flattened_arr = reshaped_arr.flatten()
print(f"Flattened array: {flattened_arr}")

# 修改 ravel 返回的视图会影响原始数组 (如果它是视图)
raveled_arr[0] = 99
print(f"Original reshaped_arr after modifying raveled view:\n{reshaped_arr}")

# T attribute or transpose(): 转置数组
print(f"\nOriginal reshaped array (3x4):\n{reshaped_arr}")
transposed_arr = reshaped_arr.T
print(f"Transposed array (4x3):\n{transposed_arr}")
print(f"Shape after transpose: {transposed_arr.shape}")

# 使用 np.newaxis 增加维度
arr1d = np.array([1, 2, 3])
print(f"\nOriginal 1D array: {arr1d}, shape: {arr1d.shape}")
row_vec = arr1d[np.newaxis, :] # 变成行向量
print(f"Row vector: {row_vec}, shape: {row_vec.shape}")
col_vec = arr1d[:, np.newaxis] # 变成列向量
print(f"Column vector:\n{col_vec}, shape: {col_vec.shape}")

## 总结

NumPy 是 Python 科学计算、机器学习和深度学习的基础。其核心 `ndarray` 对象和相关的函数提供了高效处理数值数据的强大能力。

**关键要点：**
*   `ndarray` 用于高效存储和操作同构数据。
*   利用索引和切片进行灵活的数据访问。
*   向量化操作和 ufuncs 显著提高性能，避免 Python 循环。
*   广播机制允许不同形状的数组进行运算。
*   `np.linalg` 提供了基本的线性代数功能。
*   `np.random` 用于生成各种随机数。
*   `reshape`, `ravel`, `transpose` 等用于操作数组形状。

熟练掌握 NumPy 是进行数据科学和机器学习工作的必备技能。建议多加练习，并查阅 NumPy 官方文档以了解更多高级功能。